### ISSUE TITLE
D4686 is outdated agane

### ISSUE THREAD

**Issue by brothermechanic** [boberfly/cycles#1]
Hello
I found your adaptive sampling patch https://developer.blender.org/D4686
Can you update it agane? It will be great
This is my build log
```
/var/tmp/portage-ondisk/portage/media-gfx/blender-9999/work/blender-9999/intern/cycles/kernel/kernel_types.h:1283:11: error: redeclaration of ‘int ccl::KernelFilm::pad1’
 1283 |   int pad1, pad2;
      |           ^
/var/tmp/portage-ondisk/portage/media-gfx/blender-9999/work/blender-9999/intern/cycles/kernel/kernel_types.h:1259:7: note: previous declaration ‘int ccl::KernelFilm::pad1’
 1259 |   int pad1;
      |       ^~~~
/var/tmp/portage-ondisk/portage/media-gfx/blender-9999/work/blender-9999/intern/cycles/kernel/kernel_types.h:1283:13: error: redeclaration of ‘int ccl::KernelFilm::pad2’
 1283 |   int pad1, pad2;
      |             ^~~~
/var/tmp/portage-ondisk/portage/media-gfx/blender-9999/work/blender-9999/intern/cycles/kernel/kernel_types.h:1260:7: note: previous declaration ‘int ccl::KernelFilm::pad2’

```
https://gist.github.com/9476a66377bf03150871f02c30c7bd9f

**Comment by boberfly** [comment]
Hey @brothermechanic 

Yeah that branch is stale, more for me to extract & merge into another branch eg. gaffer-adaptive & keep tabs on the official updates of the patch so I wouldn't use it. Perhaps try the [gaffer-experimental2](https://github.com/boberfly/cycles/tree/gaffer-experimental2) branch for the most up-to-date working cycles with adaptive-sampling. The error that you are seeing is very common prior to merging different patches as the kernel code needs the correct padding based on added/removed values from upstream changes/other patches.

Cheers!
